-- Creates database hbtn_0d_2 and user_0d_2 with SELECT privilege

CREATE DATABASE IF NOT EXISTS hbtn_0d_2;

CREATE USER IF NOT EXISTS 'user_0d_2'@'localhost' IDENTIFIED BY 'user_0d_2_pwd';

GRANT SELECT ON hbtn_0d_2.* TO 'user_0d_2'@'localhost';

REVOKE AUDIT_ABORT_EXEMPT,
AUTHENTICATION_POLICY_ADMIN,
FIREWALL_EXEMPT,
GROUP_REPLICATION_STREAM,
PASSWORDLESS_USER_ADMIN,
SENSITIVE_VARIABLES_OBSERVER,
TELEMETRY_LOG_ADMIN
ON *.* FROM 'user_0d_2'@'localhost';
